config/routes.rb
Rails.application.routes.draw do

  root 'top#home'

  get '/about',      to: 'top#about'
  get '/contact',   to: 'contacts#new'
  post '/contact',   to: 'contacts#create'
  get '/signup',     to: 'users#new'
  post '/signup',    to: 'users#create'
  get '/login',      to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/search',     to: 'search#search'
  get '/followers',  to: 'relationships#followers'
  get '/followings', to: 'relationships#followings'

  resources :users do
    member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image, ImageUploader
    before_save { self.email = email.downcase }

    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :relationships, dependent: :destroy

    #架空のfollowingクラス(モデル)を作成、throughで中間テーブルはrelationshipsと設定
    #sourceでrelationshipsテーブルのfollow_idを参考に、followingsモデルにアクセス
    #user.followingsと打つだけで、userが中間テーブルrelationshipsを取得し、
    #その1つ1つのrelationshipのfollow_idからフォローしているUser達を取得している
    has_many :followings, through: :relationships, source: :follow, dependent: :destroy

    #「has_many :relaitonships」の逆方向、reverse_of_relationshipsという架空のテーブル
    #class_name:でrelationsipモデルの事と設定し、relaitonshipsテーブルにアクセスする時、follow_idを入口とする
    has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy

     #架空のfollowersクラス
    has_many :followers, through: :reverse_of_relationships, source: :user, dependent: :destroy

    has_many :likes, dependent: :destroy
    # 「liked_posts」によってuserがどの投稿をいいねしているのか取得できるようになる
    has_many :liked_posts, through: :likes, source: :post

    #仮想の属性の作成
    attr_accessor :remember_token

    VALID_UNIQUE_NAME_REGEX = /\A[a-z0-9_]+\z/i
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :name,   presence: true, length: { maximum: 50 }
    validates :unique_name, presence: true, length: { in: 2..15 }, format: { with: VALID_UNIQUE_NAME_REGEX },
                            uniqueness: { case_sensitive: false }
    validates :email,  presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false },
                       format: { with: VALID_EMAIL_REGEX }
    #セキュアにハッシュ化したパスワードをpassword_digestに保存、仮想のpassword属性が自動で作成される
    has_secure_password
    validates :password, presence: true, length: { minimum: 8 }, allow_nil: true
    validates :profile, length: { maximum: 100 }

    #渡された文字列のハッシュ値を返す
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    #ライブラリの[SecureRandom]モジュール[urlsafe_base64]によってランダムなトークンを返す
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        #[update_attribute]を使って記憶ダイジェストの更新、バリデーションを素通りする
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # 記憶ダイジェストをnilに更新し、ユーザーのログイン情報を破棄
    def forget
        update_attribute(:remember_digest, nil)
    end

    #フォローするメソッド
    def follow(other_user)
        #フォローしようとしている other_user が自分自身ではないかを検証
        unless self == other_user
        self.relationships.find_or_create_by(follow_id: other_user.id)
        end
    end

    #フォロー解除
    def unfollow(other_user)
        relationship = self.relationships.find_by(follow_id: other_user.id)
        relationship.destroy if relationship
    end

    def following?(other_user)
        self.followings.include?(other_user)
    end

    private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:update, :index, :show]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def index
    @users = User.all.paginate(page: params[:page], per_page: 20)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "登録完了！ようこそ！"
      redirect_to @user
    else
      flash[:danger] = "ぴえん"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "編集完了！"
      redirect_to @user
    else
      flash[:danger] = "ぴぴぴえん"
      render :edit
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:danger] = "ぴえん"
    redirect_to users_path
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private

   def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :profile, :unique_name )
   end

   def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_info.html.erb
<div class="row">
    <div class="info_image">
        <% if @user.image? %>
            <%= image_tag @user.image.url, :size => '128x128' %>
        <% else %>
            <%= image_tag 'default.png', :size => '128x128' %>
        <% end %>
    </div>
    <div class="info_name">
        <span class="info_user_name"><%= @user.name %></span>
        <span>(<%= @user.unique_name %>)<%= render 'relationships/follow_button', user: @user %></span>
        <p><%= @user.profile %></p>
    </div>
</div>
<div class="info_follow">
    <p>
    <% if current_user?(@user)%>
        <%= link_to "[プロフィール編集]", edit_user_path(@user) %>　
    <% end %>
        <%= link_to "フォロー：#{@user.followings.count}人", following_user_path(@user) %>　
        <%= link_to "フォロワー：#{@user.followers.count}人", followers_user_path(@user) %>
    </p>
</div>

<% if current_user?(@user)%>
    <div class="info_post">
        <%= render 'posts/new_form' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
    <h1>プロフィール編集</h1>
    <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
            現在のプロフィール画像<br>
            <% if @user.image? %>
                <%= image_tag @user.image.url, :size => '128x128' %>
            <% else %>
                <%= image_tag 'default.png', :size => '128x128' %>
            <% end %>
            <div class="form-group">
            プロフィール画像の変更<br><%= f.file_field :image %>
            </div>
        </div>
        <div class="form-group">
            <label>名前</label>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
            <label>unique_name</label>
            <%= f.text_field :unique_name, class: "form-control" %>
        </div>
        <div class="form-group">
            <label>メールアドレス</label>
            <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
            <label>プロフィール編集</label><br>
            <%= f.text_area :profile, class: "form-control" %>
        </div>
            <%= f.submit "送信", class: "btn btn-primary" %>　
            <%= link_to "[ユーザー削除]", user_path(@user), method: :delete, data: { confirm: "本当に削除しちゃう?" } %>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<h1>ユーザ一覧</h1>
<div>
    <% @users.each do |user| %>
        <li class="post_item">
            <div>
                <p>
                    <% if user.image? %>
                        <%= image_tag user.image.url, :size => '40x40' %>
                    <% else %>
                        <%= image_tag 'default.png', :size => '40x40' %>
                    <% end %>
                    <%= link_to user.name, user_path(user), class: "h4" %>（
                    <% if current_user.admin? && !current_user?(user) %>
                        <%= user.unique_name %>
                    <% else %>
                        管理者
                    <% end %>
                    ）
                    <% if current_user.admin? && !current_user?(user) %>
                    ｜　管理者権限：<%= link_to "[ユーザ削除]", user, method: :delete,
                                                data: { confirm: "本当に削除しちゃう？" } %>
                    <% end %>
                </p>
                <p><%= user.profile %></p>
                <span>
                    <%= link_to "フォロー：#{user.followings.count}人", following_user_path(user) %>
                    <%= link_to "フォロワー：#{user.followers.count}人", followers_user_path(user) %>
                </span>
                <% unless current_user?(user) %>
                    <% if current_user.following?(user) %>
                        <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                            <%= f.hidden_field :follow_id, value: user.id %>
                            <%= f.submit 'フォロー解除', class: "btn btn-danger btn-sm" %>
                        <% end %>
                    <% else %>
                        <%= form_for(current_user.relationships.build) do |f| %>
                            <%= f.hidden_field :follow_id, value: user.id %>
                            <%= f.submit 'フォローする', class: "btn btn-primary btn-sm" %>
                        <% end %>
                    <% end %>
                <% end %>
                </span>
            </div>
        </li>
        <%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt',
        renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
    <% end %>
</div>

app/views/users/new.html.erb
<div id="login">
<h1 class="text-center" >新規登録</h1>
<%= form_with model: @user, local: true do |f| %>
    <div class="form-group">
        <label>名前</label>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>ID</label>
        <%= f.text_field :unique_name, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>メールアドレス</label>
        <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>パスワード</label>
        <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>パスワード再入力</label>
        <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>プロフィール文</label><br>
        <%= f.text_area :profile, class: "form-control" %>
    </div>
    <div>
        <label>プロフィール画像の設定</label><br>
        <%= f.file_field :image %>
    </div>
    <div class="text-center mt-2">
    <%= f.submit "登録する", class: "btn btn-primary w-50" %>
    </div>
<% end %>
</div>

app/views/users/show.html.erb
<div>
    <%= render 'users/user_info'%>
</div>
<div class="row">
    <div class="col-md-6 mt-2 pt-2 border-top border-dark">
        <% if @user.posts.any? %>
            <h4 class="text-center" ><%= "#{@user.name}さんの投稿 (#{@user.posts.count})" %></h4>
            <% @user.posts.each do |post| %>
                <li class="post_item">
                    <div>
                        <% if post.user.image? %>
                        <%= image_tag post.user.image.url, :size => '40x40' %>
                        <% else %>
                        <%= image_tag 'default.png', :size => '40x40' %>
                        <% end %>
                        <%= link_to post.user.name, post.user, class: "text-dark h4" %>（<%= post.user.unique_name %>）
                    </div>

                    <div class="ml-3 mt-2" >
                        <p><%= link_to post.content, post_path(post), class: "text-dark" %></p>
                        <% if post.image? %>
                        <%= image_tag post.image.url %>
                        <% end %>
                    </div>
                    <%= render 'likes/like_button', post: post%>
                    <div>
                        <% if post.user == current_user %>
                        <%= link_to "[投稿を削除する]", post_path(post), method: :delete %><br>
                        <% end %>
                        いいね: <%= post.likes.count %>　コメント：<%= post.comments.count %>　
                        <%= time_ago_in_words(post.created_at) %>前に投稿
                    </div>
                </li>
            <% end %>
        <% else %>
            <p class="text-center" >投稿はありません</p>
        <% end %>
    </div>
    <div class="col-md-6 mt-2 pt-2 border-top border-dark">
        <h4 class="text-center"><%= @user.name %>さんのしたいいね(<%= @user.likes.count %>)</h4>
        <% if @user.liked_posts.any? %>
            <% @user.liked_posts.each do |post| %>
                <li class="post_item">
                    <div>
                        <% if post.user.image? %>
                        <%= image_tag post.user.image.url, :size => '40x40' %>
                        <% else %>
                        <%= image_tag 'default.png', :size => '40x40' %>
                        <% end %>
                        <%= link_to post.user.name, post.user, class: "text-dark h4" %>（<%= post.user.unique_name %>）
                    </div>

                    <div class="ml-3 mt-2" >
                        <p><%= link_to post.content, post_path(post), class: "text-dark" %></p>
                        <% if post.image? %>
                        <%= image_tag post.image.url %>
                        <% end %>
                    </div>
                    <%= render 'likes/like_button', post: post%>
                    <div>
                        <% if post.user == current_user %>
                        <%= link_to "[投稿を削除する]", post_path(post), method: :delete %><br>
                        <% end %>
                        いいね: <%= post.likes.count %>　コメント：<%= post.comments.count %>　
                        <%= time_ago_in_words(post.created_at) %>前に投稿
                    </div>
                </li>
            <% end %>
        <% else %>
            <p class="text-center" >いいねした投稿はありません</p>
        <% end %>
    </div>
</div>

app/views/users/show_follow.html.erb
<% if @user.followings.count != 0 %>
  <h4><%= "#{@user.name}さんがふぉろーしています(#{@user.followings.count})" %></h4>
  <% @user.followings.each do |user| %>
    <li class="mb-2">
      <% if user.image? %>
          <%= image_tag user.image.url, :size => '40x40' %>
      <% else %>
          <%= image_tag 'default.png', :size => '40x40' %>
      <% end %>
      <%= link_to user.name, user_path(user), class: "h5" %> （<%= user.unique_name %>）
    </li>
  <% end %>
<% else %>
  <h4>フォローしている人はいません。ぴえん</h4>
<% end %>

app/views/users/show_follower.html.erb
<% if @user.followers.count != 0 %>
  <h4><%= "#{@user.name}さんのフォロワー(#{@user.followings.count})" %></h4>
  <% @user.followers.each do |user| %>
    <li class="mb-2">
    <% if user.image? %>
        <%= image_tag user.image.url, :size => '40x40' %>
    <% else %>
        <%= image_tag 'default.png', :size => '40x40' %>
    <% end %>
    <%= link_to user.name, user_path(user), class: "h5" %> （<%= user.unique_name %>）
  </li>
  <% end %>
<% else %>
  <h4>フォロワーはいません。ぴえん</h4>
<% end %>