config/routes.rb
Rails.application.routes.draw do

  root 'top#home'

  get '/about',      to: 'top#about'
  get '/contact',   to: 'contacts#new'
  post '/contact',   to: 'contacts#create'
  get '/signup',     to: 'users#new'
  post '/signup',    to: 'users#create'
  get '/login',      to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/search',     to: 'search#search'
  get '/followers',  to: 'relationships#followers'
  get '/followings', to: 'relationships#followings'

  resources :users do
    member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  #「liked_users」によって投稿が誰にいいねされているのか取得できるようになる
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy

  default_scope -> { order(created_at: :desc) } #ラムダ式、降順にする
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

   # マイクロポストをいいねする
   def like(user)
    likes.create(user_id: user.id)
  end

  # マイクロポストのいいねを解除する
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :new]

  def new
    @post = Post.new
  end

  def index
    @post  = current_user.posts.build
    @posts = Post.paginate(page: params[:page], per_page: 5)
    @like = Like.new
  end

  def show
    @post = Post.find(params[:id])
    @like = Like.new
    @comment = Comment.new
    @comments = @post.comments
  end

  def create
    @post = current_user.posts.new(post_params)
     # @から始まり、半角英数またはアンダースコアが5回以上、15回以下の繰り返しにマッチ。大文字、小文字区別しない。
    re = /@([0-9a-z_]{5,15})/i
    # 投稿文に対して上記正規表現をマッチング
    @post.content.match(re)
    # $1は正規表現の中の丸かっこの表現にマッチする内容が入る(つまりここでは一意ユーザ名)
    # マッチするものが無ければnil
    if $1
      # マッチした一意ユーザ名は小文字にしてから検索
      reply_user = User.find_by(unique_name: $1.downcase)
      # 一意ユーザ名を持つ返信先ユーザが存在すればin_reply_toカラムにそのユーザIDをセット
      @post.in_reply_to = reply_user.id if reply_user
    end
    if @post.save
      flash[:success] = "投稿完了！"
      redirect_to post_path(@post)
    else
      @feed_items = []
      flash[:danger] = "ぴえん"
      redirect_to current_user
    end
  end

  def update
  end

  def destroy
    @post = Post.find_by(params[:id])
    @post.destroy
    flash[:warning] = "削除しました"
    redirect_to current_user
  end

  private

  def post_params
    params.require(:post).permit(:content, :image)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_new_form.html.erb
<div class="border border-dark rounded mb-3">
  <div class="post_form">
    <h4>投稿する</h4>
    <%= form_with model: @post, url: posts_path, local: true do |f| %>
      <div class="form-group">
      <%= f.text_area :content, class: "form-control" %>
      </div>
      <div  class="form-group">
        画像<br>
        <%= f.file_field :image%>
      </div>
      <div class="form-group">
        <%= f.submit "投稿する", class: "btn btn-primary btn-sm" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<li class="post_item">
  <div>
    <% if post.user.image? %>
      <%= image_tag post.user.image.url, :size => '40x40' %>
    <% else %>
      <%= image_tag 'default.png', :size => '40x40' %>
    <% end %>
      <%= link_to post.user.name, post.user, class: "text-dark h4" %>（<%= post.user.unique_name %>）
  </div>

  <div class="ml-3 mt-2" >
    <p><%= link_to post.content, post_path(post), class: "text-dark" %></p>
    <% if post.image? %>
      <%= image_tag post.image.url %>
    <% end %>
  </div>

  <div>
    <% if post.user == current_user %>
      <%= link_to "[投稿を削除する]", post_path(post), method: :delete %><br>
    <% end %>
    いいね: <%= post.likes.count %>　コメント：<%= post.comments.count %>　
    <%= time_ago_in_words(post.created_at) %>前に投稿
  </div>
</li>

app/views/posts/index.html.erb
<div>
  <h1>最新投稿一覧</h1>
    <%= render @posts %>
  <%= will_paginate @posts, :previous_label => ' &lt 前へ', :next_label => '次へ &gt',
      renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
</div>

app/views/posts/new.html.erb
<h2>投稿する</h2>
<%= form_with model: @post, url: posts_path, local: true do |f| %>
  <div>
  <%= f.text_area :content %>
  </div>
  <div>
    画像<br>
    <%= f.file_field :image %>
  </div>
  <div>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="row">
  <h1>投稿詳細ページ</h1>
  <div class="col-12">
    <div class="post_item">
      <div>
      <% if @post.user.image? %>
        <%= image_tag @post.user.image.url, :size => '40x40' %>
      <% else %>
        <%= image_tag 'default.png', :size => '40x40' %>
      <% end %>
        <%= link_to @post.user.name, @post.user, class: "text-dark h4" %>（<%= @post.user.unique_name %>）
      </div>

      <div class="ml-3 mt-2" >
        <p><%= link_to @post.content, post_path(@post), class: "text-dark" %></p>
        <% if @post.image? %>
          <%= image_tag @post.image.url %>
        <% end %>
      </div>

      <div>
        <%= render 'likes/like_button', post: @post %>
        <% if @post.user == current_user %>
          <%= link_to "[投稿を削除する]", post_path(@post), method: :delete %><br>
        <% end %>
          <%= time_ago_in_words(@post.created_at) %>前に投稿
      </div>
    </div>
  </div>

  <div class="col-12 mb-2">
    <%= form_with model: [@post, @comment], local: true do |f| %>
      <div class="form-group">
        <%= f.text_area :content, class: "form-control w-75" %>
      </div>
      <div class="actions">
        <%= f.submit "コメントする", class: "btn btn-primary btn-sm" %>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 mt-2 pt-2 border-top border-dark">
    <h5>いいねしたユーザー(<%= @post.liked_users.count %>)</h5>
    <% @post.liked_users.each do |user| %>
      <li class="mb-2">
        <% if user.image? %>
          <%= image_tag user.image.url, :size => '30x30' %>
        <% else %>
          <%= image_tag 'default.png', :size => '30x30' %>
        <% end %>
          <%= link_to user.name, user_path(user), class: "h5" %>
        </li>
    <% end %>
  </div>

  <div class="col-md-6 mt-2 pt-2 border-top border-dark">
    <h5>コメント(<%= @comments.count %>)</h5>
    <div>
      <% @comments.each do |comment| %>
        <li class="post_item">
          <% if comment.user.image? %>
            <%= image_tag comment.user.image.url, :size => '30x30' %>
          <% else %>
            <%= image_tag 'default.png', :size => '30x30' %>
          <% end %>
          <%= link_to "#{comment.user.name}さん", user_path(comment.user), class: "h5" %>
          <p class="pt-2 pl-2"><%= comment.content %></p>
          <% if comment.user == current_user %>
            <span><%= link_to "[コメントを削除する]", post_comment_path(comment.post_id, comment.id), method: :delete %></span>
          <% end %>
          <%= time_ago_in_words(comment.created_at) %>前に投稿
        </li>
      <% end %>
    </div>
  </div>
</div>