config/routes.rb
Rails.application.routes.draw do

  root 'top#home'

  get '/about',      to: 'top#about'
  get '/contact',   to: 'contacts#new'
  post '/contact',   to: 'contacts#create'
  get '/signup',     to: 'users#new'
  post '/signup',    to: 'users#create'
  get '/login',      to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/search',     to: 'search#search'
  get '/followers',  to: 'relationships#followers'
  get '/followings', to: 'relationships#followings'

  resources :users do
    member do
     get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

end

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="navbar fixed-bottom">
  <div class="continer">
  <nav>
    <ul class="navbar-nav">
      <li　class="nav-item"><%= link_to "ホーム", root_path %></li>
      <li　class="nav-item"><%= link_to "アバウト", about_path %></li>
      <li　class="nav-item"><%= link_to "お問い合わせ", contact_path %></li>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
<div class="container">
    <%= link_to "アプリ", root_path, id: "logo"%>
    <nav id="nav">
        <ul class="navbar-nav navbar-right navbar-dark"> 
            <% if logged_in? %>
                <li　class="nav-item"><%= link_to "ログアウト", logout_path, method: :delete, class: "text-dark" %></li>
                <li　class="nav-item"><%= link_to "ユーザー一覧", users_path, class: "text-dark"  %></li>
                <li　class="nav-item"><%= link_to "最新投稿一覧", posts_path, class: "text-dark"  %></li>
            <%else%>
                <li　class="nav-item"><%= link_to "新規登録", signup_path, class: "text-dark"  %></li>
            <% end %>
        </ul>
    </nav>
</div>

</header>

app/views/layouts/_search_form.html.erb
<div class="row search_bar">
    <div class="search_name col-md-6">
      ログイン中：<% if @current_user.image? %>
      <%= image_tag @current_user.image.url, :size => '30x30' %>
      <% else %>
        <%= image_tag 'default.png', :size => '30x30' %>
      <% end %>
      <%= link_to @current_user.name, user_path(@current_user), class: "text-dark" %>
    </div>

    <div class="search_form col-md-6">
      <%= form_with url: search_path, method: :get, local: true do |f| %>
        <%= f.text_field :content%>
        <%= f.select :model, [["ユーザー", "user"], ["投稿", "post"]]%>
        <%= f.submit '検索する', class: "btn btn-success btn-sm" %>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <div class="container">
      <% if logged_in? %>
        <%= render 'layouts/search_form'%>
      <% end %>
      <%= render 'layouts/flash_message' %>

      <%= yield %>
      <div class="footer">
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>